/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tugip;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appEmptyTest() {
        App classUnderTest = new App();
    }
}
