/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tugip;

import static hu.kwu.tugip.App.SYSTEM_SOUND_DIRS;
import hu.kwu.tugip.Director;
import hu.kwu.tugip.Sounder;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class DirectorTester {

    public final static Sounder S = new Sounder(SYSTEM_SOUND_DIRS[2] + "hello.wav");

    @Test
    void appEmptyTest() {
        Assertions.assertTrue("[1, 40, 100, 3]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(341))));
        Assertions.assertTrue("[1, 20on, 100, 5]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(521))));
        Assertions.assertTrue("[9, 90, 100, 8]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(899))));
        Assertions.assertTrue("[9, 90, 100, 9]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(999))));
        Assertions.assertTrue("[1000]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(1000))));
        Assertions.assertTrue("[1, 1000]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(1001))));
        Assertions.assertTrue("[100, 2, 1000]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(1200))));
        Assertions.assertTrue("[1000, 2]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(2000))));
        Assertions.assertTrue("[1000, 3]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(3000))));
        Assertions.assertTrue("[1000, 1, 10en, 100]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(111000))));
        Assertions.assertTrue("[3, 30, 100, 3, 1000, 6, 60, 100, 6]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(666333))));
        Assertions.assertTrue("[3, 30, 100, 3, 1000, 6, 60, 100, 6]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(666333))));
        Assertions.assertTrue("[9, 1000, 4, 90, 100, 2]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(294009))));
        Assertions.assertTrue("[5, 1000, 8, 40, 100, 5]".equals(java.util.Arrays.toString(Director.generateNumberFileNames(548005))));
    }
}
